export default [
    "Accountancy",
    "Acting",
    "Advertising Arts",
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Agribusiness Management",
    "Agricultural and Biosystems Engineering",
    "Agricultural Business",
    "Agricultural Economics",
    "Agricultural Extension",
    "Agricultural Science",
    "Agriculture",
    "Animal Science",
    "Animation",
    "Anthropology",
    "Applied Chemistry",
    "Applied Economics",
    "Applied Linguistics",
    "Applied Mathematics",
    "Applied Physics",
    "Aquaculture",
    "Architecture",
    "Art Conservation",
    "Art History",
    "Arts and Design",
    "Asian Studies",
    "Astronomy",
    "Automotive Engineering",
    "Baking and Pastry Arts",
    "Banking and Finance",
    "Behavioral Science",
    "Biochemistry",
    "Bioengineering",
    "Bioinformatics",
    "Biological Engineering",
    "Biological Science",
    "Biology",
    "Biomedical Engineering",
    "Biomedical Science",
    "Biophysics",
    "Biotechnology",
    "Botany",
    "Broadcast Communication",
    "Business Administration",
    "Business Analytics",
    "Business Law",
    "Business Management",
    "Chemical Engineering",
    "Chemistry",
    "Child Development",
    "Chiropractic Medicine",
    "Civil Engineering",
    "Classical Studies",
    "Climate Science",
    "Communication",
    "Community Development",
    "Comparative Literature",
    "Computational Biology",
    "Computer Animation",
    "Computer Engineering",
    "Computer Forensics",
    "Computer Graphics",
    "Computer Science",
    "Computer Security",
    "Computer Systems Engineering",
    "Construction Management",
    "Conservatory of Music",
    "Counseling Psychology",
    "Creative Writing",
    "Criminology",
    "Culinary Arts",
    "Cybersecurity",
    "Data Science and Analytics",
    "Dental Hygiene",
    "Dentistry",
    "Development Communication",
    "Development Studies",
    "Digital Arts",
    "Digital Marketing",
    "Disaster Risk Management",
    "Drama",
    "Early Childhood Education",
    "Earth Science",
    "East Asian Studies",
    "Ecological Engineering",
    "Ecology",
    "Economics",
    "Educational Management",
    "Educational Psychology",
    "Educational Technology",
    "Electrical Engineering",
    "Electronics Engineering",
    "Elementary Education",
    "Energy Engineering",
    "Engineering Management",
    "English Language Studies",
    "English Literature",
    "Entrepreneurship",
    "Environmental Engineering",
    "Environmental Management",
    "Environmental Planning",
    "Environmental Science",
    "Ethnomusicology",
    "European Studies",
    "Event Management",
    "Exercise and Sports Science",
    "Fashion Design and Merchandising",
    "Film and Television Studies",
    "Film Studies",
    "Finance",
    "Fine Arts",
    "Fisheries and Aquatic Resources",
    "Food Engineering",
    "Food Science and Nutrition",
    "Food Technology",
    "Forestry",
    "Forensic Accounting",
    "Forensic Psychology",
    "Forensic Science",
    "French Studies",
    "Game Development",
    "Gender Studies",
    "General Studies",
    "Genetic Engineering",
    "Genetics",
    "Geodetic Engineering",
    "Geography",
    "Geological Engineering",
    "Geology",
    "Geophysics",
    "German Studies",
    "Global Studies",
    "Graphic Arts",
    "Graphic Design",
    "Guidance and Counseling",
    "Health Administration",
    "Health Informatics",
    "Health Science",
    "Heritage Conservation",
    "Hispanic Studies",
    "History",
    "Horticulture",
    "Hospitality Management",
    "Hotel and Restaurant Management",
    "Human Biology",
    "Human Resource Management",
    "Human Services",
    "Humanities",
    "Industrial Chemistry",
    "Industrial Design",
    "Industrial Engineering",
    "Industrial Psychology",
    "Information Management",
    "Information Science",
    "Information Systems",
    "Information Technology",
    "Innovation and Entrepreneurship",
    "Insurance and Risk Management",
    "Interior Architecture",
    "Interior Design",
    "International Business",
    "International Relations",
    "International Studies",
    "Islamic Studies",
    "Japanese Studies",
    "Journalism",
    "Landscape Architecture",
    "Language and Literature",
    "Law",
    "Legal Management",
    "Library and Information Science",
    "Linguistics",
    "Literature",
    "Management Accounting",
    "Management Information Systems",
    "Manufacturing Engineering",
    "Marine Biology",
    "Marine Engineering",
    "Marine Science",
    "Marketing",
    "Marketing Communication",
    "Mass Communication",
    "Materials Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Media and Communication Studies",
    "Medical Laboratory Science",
    "Medical Technology",
    "Medicine",
    "Metallurgical Engineering",
    "Meteorology",
    "Microbiology",
    "Midwifery",
    "Military Science",
    "Mining Engineering",
    "Molecular Biology and Biotechnology",
    "Multimedia Arts",
    "Museum Studies",
    "Music",
    "Nanotechnology",
    "Naval Architecture",
    "Network Administration",
    "Neuroscience",
    "Nursing",
    "Nutrition and Dietetics",
    "Occupational Therapy",
    "Oceanography",
    "Office Administration",
    "Operations Management",
    "Optometry",
    "Organizational Communication",
    "Painting",
    "Performing Arts",
    "Petroleum Engineering",
    "Pharmaceutical Sciences",
    "Pharmacy",
    "Philosophy",
    "Photography",
    "Physical Education",
    "Physical Therapy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Publishing",
    "Radiologic Technology",
    "Real Estate Management",
    "Religious Studies",
    "Renewable Energy Engineering",
    "Respiratory Therapy",
    "Robotics Engineering",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Special Education",
    "Speech Communication",
    "Speech-Language Pathology",
    "Sports Management",
    "Statistics",
    "Structural Engineering",
    "Sustainable Agriculture",
    "Sustainable Energy",
    "Teacher Education",
    "Telecommunications Engineering",
    "Textile Engineering",
    "Theater Arts",
    "Tourism Management",
    "Translation and Interpretation",
    "Veterinary Medicine",
    "Web Development",
    "Wildlife Biology",
    "Women’s Studies"
];

