export default [
    "Accountancy",
    "Agriculture",
    "Architecture",
    "Arts and Design",
    "Business Administration",
    "Civil Engineering",
    "Communication",
    "Computer Engineering",
    "Computer Science",
    "Criminology",
    "Culinary Arts",
    "Education",
    "Electrical Engineering",
    "Electronics Engineering",
    "Entrepreneurship",
    "Environmental Science",
    "Fine Arts",
    "Hospitality Management",
    "Human Resource Management",
    "Industrial Engineering",
    "Information Technology",
    "Journalism",
    "Law",
    "Marketing",
    "Marine Biology",
    "Mass Communication",
    "Mechanical Engineering",
    "Medical Technology",
    "Medicine",
    "Midwifery",
    "Music",
    "Nursing",
    "Pharmacy",
    "Physical Education",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Social Work",
    "Software Engineering",
    "Tourism Management",
    "Veterinary Medicine"
]
