export default [
    "Master in Art Therapy",
    "Master in Cultural Studies",
    "Master in Museum Studies",
    "Master of Arts in Digital Humanities",
    "Master of Arts in Creative Writing",
    "Master of Arts in Journalism",
    "Master in Conflict Resolution and Peace Studies",
    "Master in Fashion Design and Merchandising",
    "Master in Game Art and Animation",
    "Master of Fine Arts",
    "Master in Accounting and Finance",
    "Master in Business Administration",
    "Master in Business Analytics",
    "Master in Corporate Innovation",
    "Master in Digital Business",
    "Master in Entrepreneurship",
    "Master in Hospitality Management",
    "Master in Global Security Studies",
    "Master in Human Rights and Social Justice",
    "Master in International Business",
    "Master in Organizational Leadership",
    "Master in Social Entrepreneurship",
    "Master in Strategic Management",
    "Master of Engineering in AI and Robotics",
    "Master of Engineering in Computer Engineering",
    "Master of Engineering in Embedded Systems",
    "Master of Science in Digital Systems Design",
    "Master of Science in Network Engineering",
    "Master in Distance Learning and eLearning Design",
    "Master in Educational Leadership",
    "Master in Inclusive Education",
    "Master in STEM Education",
    "Master in Health Informatics",
    "Master in Nursing",
    "Master in Cyber Law",
    "Master in Environmental Law",
    "Master in International Business Law",
    "Master in International Humanitarian Law",
    "Master in Nutrition and Dietetics",
    "Master in Public Health",
    "Master of Science in Epidemiology",
    "Master of Science in Medical Imaging",
    "Master of Science in Neuroscience",
    "Master of Science in Sports Medicine",
    "Master of Science in Astrophysics",
    "Master of Science in Biotechnology",
    "Master of Science in Genomics",
    "Master of Arts in Language and Literacy Education",
    "Master in Civil Engineering",
    "Master in Electrical Engineering",
    "Master in Environmental Engineering",
    "Master in Geotechnical Engineering",
    "Master in Mechanical Engineering",
    "Master in Structural Engineering",
    "Master in Transportation Engineering",
    "Master of Engineering in Mechatronics",
    "Master of Engineering in Renewable Energy Systems",
    "Master of Science in Climate Change Adaptation",
    "Master of Science in Environmental Science",
    "Master of Science in Marine and Coastal Management",
    "Master of Science in Sustainability Management",
    "Master of Science in Urban Sustainability",
    "Master of Science in Urban Sociology",
    "Master in Artificial Intelligence",
    "Master in Blockchain Technology",
    "Master in Cloud Computing",
    "Master in Cybersecurity",
    "Master in Data Science",
    "Master in Game Development",
    "Master in Human-Computer Interaction",
    "Master in Information Systems",
    "Master in Information Technology",
    "Master in Software Engineering",
    "Master in Virtual and Augmented Reality",
    "Doctor of Education (Ed.D)",
    "Doctor of Education in Educational Policy",
    "Doctor of Education in Curriculum and Instruction",
    "Doctor of Education in Distance Education",
    "Doctor of Education in Special Education",
    "Doctor of Education in Teacher Leadership",
    "Doctor of Engineering in Materials Science",
    "Doctor of Engineering in Offshore Engineering",
    "Doctor of Engineering in Structural Engineering",
    "Doctor of Engineering in Sustainable Energy",
    "Doctor of Engineering in Urban Infrastructure",
    "Doctor of Engineering in Aerospace Engineering",
    "Doctor of Philosophy in Business Administration",
    "Doctor of Philosophy in Business Analytics",
    "Doctor of Philosophy in Criminal Justice",
    "Doctor of Philosophy in Cybersecurity",
    "Doctor of Philosophy in Marketing",
    "Doctor of Philosophy in Musicology",
    "Doctor of Philosophy in Pharmaceutical Sciences",
    "Doctor of Philosophy in Political Economy",
    "Doctor of Philosophy in Organizational Behavior",
    "Doctor of Philosophy in Quantum Computing",
    "Doctor of Philosophy in Renewable Energy Studies",
    "Doctor of Philosophy in Risk Management",
    "Doctor of Philosophy in Supply Chain Management",
    "Doctor of Philosophy in Theatre Studies",
    "Doctor of Information Technology",
    "Doctor of Philosophy in Artificial Intelligence",
    "Doctor of Philosophy in Data Science",
    "Doctor of Philosophy in Game Design and Development",
    "Doctor of Science in Computational Biology",
    "Doctor of Science in Human-Computer Interaction",
    "Doctor of Philosophy in Biodiversity Conservation",
    "Doctor of Philosophy in Environmental Management",
    "Doctor of Philosophy in Sustainable Development",
    "Doctor of Public Health (DrPH)",
    "Doctor of Philosophy in Biomedical Sciences",
    "Doctor of Philosophy in Clinical Psychology",
    "Doctor of Philosophy in Regenerative Medicine",
    "Doctor of Juridical Science",
    "Doctor of Philosophy in Environmental Law",
    "Doctor of Philosophy in International Law",
    "Doctor of Engineering in Computer Engineering",
    "Doctor of Engineering in Robotics and Automation",
    "Doctor of Philosophy in Computer Systems Engineering",
    "Doctor of Philosophy in Computational Science",
    "Doctor of Arts in Performing Arts",
    "Doctor of Philosophy in Aesthetic Studies",
    "Doctor of Philosophy in Visual Arts",
    "Doctor of Philosophy in Gender Studies",
    "Doctor of Philosophy in Global Development",
    "Doctor of Philosophy in Migration Studies",
    "Doctor of Philosophy in Political Science",
    "Doctor of Philosophy in Quantum Chemistry",
    "Doctor of Science in Biophysics",
    "Doctor of Science in Nanotechnology"
];
